config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  root 'static_pages#home'

  resources :tests, only: [] do
    member do
      resources :responses, only: [:new, :create]
    end
  end

  resources :responses, only: [] do
    member do
      get :result, to: 'results#show'
    end
  end
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id           :bigint           not null, primary key
#  answer_text  :string
#  answer_value :integer
#  question_id  :bigint           not null
#  response_id  :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :response

  has_one :responder, through: :response

  validates :answer_text, presence: true, if: ->{ question&.text? }
  validates :answer_value, presence: true, if: ->{ question&.multiple_choice? || question&.true_false?  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id             :bigint           not null, primary key
#  title          :string
#  caption        :string
#  test_id        :bigint           not null
#  question_type  :integer          default("multiple_choice")
#  question_order :integer          default(0)
#  settings       :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Question < ApplicationRecord
  belongs_to :test
  has_one :author, through: :test

  validates :caption, presence: true, length: { maximum: 255 }
  
  before_save :set_true_false_choices, if: ->{ true_false? }

  enum question_type: { multiple_choice: 0, true_false: 1, text: 2 }

  store :settings, accessors: [:choices]

  private

  def set_true_false_choices
    self.choices = [{order: 0, caption: "True", value: true}, {order: 1, caption: "False",value: false}]
  end
end

app/models/response.rb
# == Schema Information
#
# Table name: responses
#
#  id           :bigint           not null, primary key
#  responder_id :bigint           not null
#  test_id      :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Response < ApplicationRecord
  belongs_to :test
  belongs_to :responder, class_name: 'User', foreign_key: 'responder_id'

  has_one :result, dependent: :destroy

  has_many :answers, dependent: :destroy
  has_many :questions, through: :answers
end

app/models/result.rb
# == Schema Information
#
# Table name: results
#
#  id                 :bigint           not null, primary key
#  response_id        :bigint           not null
#  score              :integer          not null
#  max_possible_score :integer          not null
#  question_count     :integer          not null
#  answer_count       :integer          not null
#  result             :string           not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Result < ApplicationRecord
  belongs_to :response
  
  has_one :test, through: :response
  has_one :responder, through: :response

  def percent_result
    (score.to_f / max_possible_score.to_f) * 100
  end
end

app/models/test.rb
# == Schema Information
#
# Table name: tests
#
#  id               :bigint           not null, primary key
#  title            :string
#  author_id        :bigint           not null
#  audience         :integer          default("open")
#  status           :integer          default("draft")
#  calculation_type :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Test < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :responses, dependent: :destroy
  has_many :responders, through: :responses, source: :responder
  has_many :questions, dependent: :destroy

  validates :title, presence: true, uniqueness: { scope: :author_id }, if: ->{ open? } 
  
  # cant use public/private because they are reserved words
  enum audience: { open: 0, closed: 1 } 
  enum status: { draft: 0, published: 1, archived: 2 }
  
  def calculation_class
    "Calculations::#{calculation_type.to_s.camelize}".constantize
  end

  alias :calculation :calculation_class
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  name            :string
#  email           :string
#  role            :integer          default("guest")
#  password_digest :string
#
class User < ApplicationRecord
  has_secure_password(validations: false)
  
  has_many :responses, dependent: :destroy
  has_many :results, through: :responses
  has_many :answers, through: :responses
  has_many :created_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :responded_tests, through: :responses, source: :test

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP },  unless: ->{ guest? } 
  validates :name, presence: true, length: { maximum: 50 }
  validates :password, presence: true, length: { minimum: 6 }, unless: ->{ guest? }
  
  enum role: { guest: 0, user: 1,  admin: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
    @response = Response.new
    @test = Test.includes(:questions).find(params[:id])
  end

  def create
    results = ResponseCreator.execute(test, response_params)
    response = results.data

    if results.success?
      redirect_to result_response_path(response)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def response_params
    params.require(:response).permit(
      responder: [:name, :id],
      answers: {}
    )
  end

  def test
    @test ||= Test.find(params[:id])
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def show
    @result = result
  end

  private

  def result
    @result = Response.includes(:result, :test).find(params[:id]).result
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @quick_test = Test.find_by(title: "Quick Personality Test")
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Persona</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'home/persona_logo.png' %>
  </head>

  <body class="bg-dark">
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/questions/_question.html.erb
<div class="row d-flex justify-content-center p-2">
  <div class="card rounded-4 border-secondary bg-transparent col-1 d-flex justify-content-center">
    <span class="h5 text-center"><%= index %></span>
  </div> 
  <div class="ms-2 card rounded-4 border-secondary bg-transparent col-8">
    <div class="card-body">
      <h4 class="card-title fw-bold py-2"><%= question.caption %></h4>
      <div class="row py-2">
        <% question.choices.each_with_index do |choice, choice_index| %>
          <%= render 'questions/question_choice', 
                question: question, 
                choice: choice, 
                choice_index: choice_index %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/_question_choice.html.erb
 
 <div class="col">
    <%= radio_button_tag(
      "response[answers][question_id:#{question.id}]", 
      choice[:value], 
      checked = false, 
      options = {
        id: "ch_#{question.id}_#{choice_index}"
      }
    )%>
    <%= label_tag(
      "ch_#{question.id}_#{choice_index}", 
      choice[:caption],
      options = {
        class: "form-check-label"
      }
    )%>
</div>

app/views/responses/new.html.erb
  <div class="container p-1 text-light">
    <div class="d-flex justify-content-center allign-items-center h1 mt-4">
      <h2 class="col-8 text-center fw-bold display-3">
        <%= @test.title %>
      </h2>
    </div>
    <div class="py-3">
    <%= simple_form_for @response, url: responses_path(@test) do |frm| %>
      <%= frm.simple_fields_for :user do |usr| %>
      <div class="my-3 d-flex justify-content-center allign-items-center">
        <div class="col-6 border border-outline border-secondary rounded-3">
          <%= usr.input :name, 
                label: "Name:",
                wrapper_html: { class: 'd-flex'},
                label_html: { class: 'text-nowrap p-2 mx-2' },
                input_html: { 
                  class: 'bg-transparent text-light border-0 text-center',
                  name: "response[responder][name]"
                }
          %>
        </div>
      </div>
      <% end %>
      <% @test.questions.each_with_index do |question, index| %>
        <%= render "questions/question", question: question, index: index+1, frm: frm %>
      <% end %>
      <div class="my-3 d-flex justify-content-center allign-items-center" >
        <%= frm.button :submit, "Save and See Results", class: "btn btn-lg btn-outline-primary"%>
      </div>
    <% end %>
    </div>
  </div>

app/views/results/show.html.erb
  <div class="container p-1 text-light">
    <div class="row flex-lg-row-reverse align-items-center justify-content-center  py-5 main-container">
      <div class="col-10">
        <div class="text-center mb-4">
          <div class="h1 display-3 fw-bold lh-1 mb-3"><%= @result.test.title %></div>
          <div class='text-center display-6'>Test Results</div>
        </div>
        <div class="border border-outline border-secondary rounded p-4 mb-4">
          <div class="row mb-4">
            <div class='col-2 fw-bold'>Name: </div>
            <div class='col-10 h1 text-center'><%= @result.responder.name %> </div>
          </div>
          <div class="row mb-2">
            <div class='col-2 fw-bold'>Score: </div>
            <div class='col-10 h4 text-center'><%= @result.score %>  </div>
          </div>
          <div class="row mb-2">
            <div class='col-2 fw-bold'>Out of: </div>
            <div class='col-10 h4 text-center'><%= @result.test.calculation.max_possible_score %>  </div>
          </div>
          <div class="row mb-2">
            <div class='col-2 fw-bold'>Percentage: </div>
            <div class='col-10 h4 text-center mb-4'><%= @result.percent_result %> %</div>
          </div>
          <div class="row mb-2">
            <span class="col-2 fw-bold"> Result: </span>
            <span class="col-10 h1 text-center"> <%= @result.result %></span>
          </div>
        </div>
        <div class="border border-outline border-secondary rounded p-4 mb-4">
          <div class="row">
            <div class='fw-bold pb-2'>Note: </div>
            <p class='text-center'>It's important to keep in mind that introversion and extroversion are complex personality traits, 
            and that people can fall anywhere on a spectrum between the two. The test can give a general idea, but not a definitive answer. 
            Additionally, people's personalities can change throughout their lives and in different situations.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_footer.html.erb
<footer class="bg-secondary text-light d-flex align-items-center justify-content-center p-4">
 <%= link_to 'https://www.linkedin.com/in/ae-cordova/', class: "text-decoration-none text-light" do %>
 <%= image_tag 'home/profile_pic.jpg', size: 40, class: "rounded-circle" %>
    Made by Angel Cordova
 <% end %>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-light bg-light">
    <div class="container">
      <%= link_to root_path, class:"navbar-brand d-flex align-items-center" do %>
        <%= image_tag 'home/persona_logo.png', alt:"persona-logo", size:"40", class:"d-inline-block align-text-top" %>
        <h2 class="ms-2 fw-bold">Persona</h2>
      <% end %>

      <div class="buttons">
        <%= link_to "Sign Up", "#", class:"btn btn-outline-dark" %>
        <%= link_to "Log In", "#", class:"btn btn-outline-dark" %>
      </div>
    </div>
  </nav>
</header>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
  <div class="container col-12 p-1 text-light h-100">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-7">
        <%= image_tag 'home/image_2.png', class:"d-block mx-lg-auto img-fluid rounded-4", width:"700", height:"500", loading:"lazy" %>
      </div>
      <div class="col-5 h-100">
        <h1 class="display-3 fw-bold text-center">Expore your true potential</h1>
        <div class="lead text-center pb-4">Sign up now for personalized tests according to your needs or give it a try with our quick sample test!</div>
        <div class=" d-flex justify-content-center pt-4">
          <%= link_to 'Take me to Quick Test!', new_response_path(id: @quick_test.id), class:"btn btn-primary btn-lg px-4 me-md-2" %>
        </div>
      </div>
    </div>
  </div>